name: liferay-stack
services:
    database:
        container_name: database
        environment:
            POSTGRES_DB: lportal
            POSTGRES_HOST_AUTH_METHOD: trust
        healthcheck:
            interval: 5s
            retries: 10
            start_period: 5m
            test: >
                pg_isready
                --username
                postgres
            timeout: 20s
        image: postgres:16
        ports:
            -   5432:5432
    liferay:
        container_name: liferay
        depends_on:
            database:
                condition: service_healthy
        environment:
            LIFERAY_CONFIGURATION_PERIOD_OVERRIDE_PERIOD_COM_PERIOD_LIFERAY_PERIOD_MAIL_PERIOD_SETTINGS_PERIOD_CONFIGURATION_PERIOD__UPPERCASEM_AIL_UPPERCASES_ETTING_UPPERCASEC_OMPANY_UPPERCASEC_ONFIGURATION_UNDERLINE_ENABLE_UPPERCASES_TART_UPPERCASET__UPPERCASEL__UPPERCASES_: 'B"false"'
            LIFERAY_CONFIGURATION_PERIOD_OVERRIDE_PERIOD_COM_PERIOD_LIFERAY_PERIOD_MAIL_PERIOD_SETTINGS_PERIOD_CONFIGURATION_PERIOD__UPPERCASEM_AIL_UPPERCASES_ETTING_UPPERCASEC_OMPANY_UPPERCASEC_ONFIGURATION_UNDERLINE_OUTGOING_UPPERCASES__UPPERCASEM__UPPERCASET__UPPERCASEP__UPPERCASEP_ORT: '"1025"'
            LIFERAY_CONFIGURATION_PERIOD_OVERRIDE_PERIOD_COM_PERIOD_LIFERAY_PERIOD_MAIL_PERIOD_SETTINGS_PERIOD_CONFIGURATION_PERIOD__UPPERCASEM_AIL_UPPERCASES_ETTING_UPPERCASEC_OMPANY_UPPERCASEC_ONFIGURATION_UNDERLINE_OUTGOING_UPPERCASES__UPPERCASEM__UPPERCASET__UPPERCASEP__UPPERCASES_ERVER: '"mail"'
            LIFERAY_CONFIGURATION_PERIOD_OVERRIDE_PERIOD_COM_PERIOD_LIFERAY_PERIOD_MAIL_PERIOD_SETTINGS_PERIOD_CONFIGURATION_PERIOD__UPPERCASEM_AIL_UPPERCASES_ETTING_UPPERCASEC_OMPANY_UPPERCASEC_ONFIGURATION_UNDERLINE_SMTP_UPPERCASEP_ASSWORD: '""'
            LIFERAY_CONFIGURATION_PERIOD_OVERRIDE_PERIOD_COM_PERIOD_LIFERAY_PERIOD_MAIL_PERIOD_SETTINGS_PERIOD_CONFIGURATION_PERIOD__UPPERCASEM_AIL_UPPERCASES_ETTING_UPPERCASEC_OMPANY_UPPERCASEC_ONFIGURATION_UNDERLINE_SMTP_UPPERCASEU_SER_UPPERCASEN_AME: '""'
            LIFERAY_CONFIGURATION_PERIOD_OVERRIDE_PERIOD_COM_PERIOD_LIFERAY_PERIOD_MAIL_PERIOD_SETTINGS_PERIOD_CONFIGURATION_PERIOD__UPPERCASEM_AIL_UPPERCASES_ETTING_UPPERCASES_YSTEM_UPPERCASEC_ONFIGURATION_UNDERLINE_SEND_UPPERCASEB_LACKLIST: '""'
            LIFERAY_DISABLE_TRIAL_LICENSE: "true"
            LIFERAY_JPDA_ENABLED: "true"
            LIFERAY_JVM_OPTS: -XX:MaxMetaspaceSize=1g -XX:MaxNewSize=2g -XX:MetaspaceSize=768m -XX:NewSize=2g -XX:SurvivorRatio=7 -Xms8g -Xmx8g
            LIFERAY_WORKSPACE_ENVIRONMENT: local
        healthcheck:
            interval: 10s
            retries: 60
            start_period: 40s
            test: >
                curl
                --fail
                --silent
                http://localhost:8080/c/portal/status
            timeout: 10s
        image: liferay:local
        mem_limit: 10g
        mem_reservation: 8g
        ports:
            -   80:8080
            -   8000:8000
            -   8080:8080
            -   11311:11311
            -   58081:58081
        volumes:
            -   liferay_data:/opt/liferay/data
            -   liferay_routes:/opt/liferay/routes
    liferay-one-etc-spring-boot:
        container_name: liferay-one-etc-spring-boot
        depends_on:
            liferay:
                condition: service_healthy
        env_file:
            -   ./client-extensions/liferay-one-etc-spring-boot/build/local.env
            -   path: ./.env.local
                required: false
        environment:
            LIFERAY_JAR_RUNNER_JAVA_OPTS: --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED
            LIFERAY_ROUTES_CLIENT_EXTENSION: /opt/liferay/routes/default/liferay-one-etc-spring-boot
            LIFERAY_ROUTES_DXP: /opt/liferay/routes/default/dxp
        healthcheck:
            interval: 10s
            retries: 30
            start_period: 60s
            test: ["CMD", "curl", "--fail", "--silent", "http://localhost:58081/ready"]
            timeout: 5s
        image: liferay-one-etc-spring-boot:latest
        network_mode: service:liferay
        volumes:
            -   liferay_routes:/opt/liferay/routes:ro
            -   ./client-extensions/liferay-one-etc-spring-boot/scripts/wait-for-routes.sh:/usr/local/bin/liferay_jar_runner_set_up.sh:ro
    mail:
        container_name: mail
        image: maildev/maildev
        ports:
            -   1025:1025
            -   1080:1080
        restart: always
volumes:
    liferay_data:
    liferay_routes: