#
# Application
#

liferay.one.etc.spring.boot.url=${LIFERAY_ONE_ETC_SPRING_BOOT_URL:http://localhost:58081}

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-one-etc-cron-oahs.oauth2.headless.server.client.secret=${LIFERAY_ONE_ETC_CRON_OAHS_CLIENT_SECRET}
liferay.oauth.application.external.reference.codes=liferay-one-etc-cron-oahs